version: '3.3'
services:
  db:
    container_name: devbook_db
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

# Name of the volume responsible for persisting the database
volumes:
  my-db:
